#!/usr/bin/env python3
"""itsUP CLI - Lean, automated, zero-downtime infrastructure management"""

import click

from commands.init import init


@click.group()
@click.version_option(version="0.1.2", prog_name="itsup")
def cli() -> None:
    """itsUP - Infrastructure management for Docker services"""
    pass


# Register commands
cli.add_command(init)


if __name__ == "__main__":
    cli()
