# Traefik configuration overrides
# This file uses native Traefik YAML schema and will be merged on top of generated config
# Edit values below, then commit to git
# Secrets referenced as ${VAR} - actual values in secrets/itsup.txt
certificatesResolvers:
  letsencrypt:
    acme:
      email: ${LETSENCRYPT_EMAIL}
      # Uncomment for Let's Encrypt staging (testing)
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
log:
  level: INFO # DEBUG, INFO, WARN, ERROR
middlewares:
  rate-limit:
    rateLimit:
      period: 1s
      average: 100
      burst: 200
experimental:
  plugins:
    bouncer:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.2.0

plugins:
  crowdsec:
    apikey: ${CROWDSEC_APIKEY}
    collections:
      - crowdsecurity/linux
      - crowdsecurity/traefik
      - crowdsecurity/http-cve
      - crowdsecurity/sshd
      - crowdsecurity/whitelist-good-actors
      - crowdsecurity/appsec-virtual-patching
    enabled: true
    options:
      crowdsecCapiMachineId: login
      crowdsecCapiPassword: password
      crowdsecCapiScenarios:
        - crowdsecurity/http-admin-interface-probing
        - crowdsecurity/http-backdoors-attempts
        - crowdsecurity/http-bad-user-agent
        - crowdsecurity/http-crawl-non_statics
        - crowdsecurity/http-generic-bf
        - crowdsecurity/http-open-proxy
        - crowdsecurity/http-path-traversal-probing
        - crowdsecurity/http-probing
        - crowdsecurity/http-sensitive-files
        - crowdsecurity/http-sqli-probing
        - crowdsecurity/http-xss-probing
        - ltsich/http-w00tw00t
      defaultDecisionSeconds: 600
      httpTimeoutSeconds: 10
      logLevel: WARN
      updateIntervalSeconds: 60
    version: v1.2.0
    # tls:
    #   stores:
    #     default:
    #       defaultGeneratedCert:
    #         domain:
    #           main: ${DOMAIN_SUFFIX}
    #           sans:
    #             - '*.${DOMAIN_SUFFIX}'
    #         resolver: letsencrypt
