# Traefik configuration overrides
# This file uses native Traefik YAML schema and will be merged on top of generated config
# Edit values below, then commit to git
# Secrets referenced as ${VAR} - deployment injects live values

# log:
#   level: INFO # DEBUG, INFO, WARN, ERROR

# experimental:
#   plugins:
#     bouncer:
#       version: v1.4.5
