name: Deploy

on:
  workflow_run:
    workflows: ['Test']
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    if: false

    steps:
      - uses: actions/checkout@v2

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

      - name: Connect to VPN
        uses: 'Morriz/github-openvpn-connect-action@v3'
        with:
          config_file: .github/workflows/client.ovpn
          host: ${{ secrets.API_HOST }}
          ca: '${{ secrets.OVPN_CA }}'
          cert: '${{ secrets.OVPN_CERT }}'
          client_key: '${{ secrets.OVPN_USER_KEY }}'
          client_pass: '${{ secrets.OVPN_USER_PASS }}'
          tls_auth_key: '${{ secrets.OVPN_TLS_AUTH_KEY }}'

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: '${{ secrets.SSH_PRIVATE_KEY }}'
          passphrase: '${{ secrets.SSH_PASSPHRASE }}'
          script: |
            curl -v 'https://${{ secrets.API_HOST }}/update-upstream/itsUP' -H 'Authorization: Bearer ${{ secrets.API_KEY }}'
            exit
